-- Table for storing lottery number recommendations generated by the chatbot.
-- Run this in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.is_valid_lottery_numbers(nums integer[])
returns boolean
language plpgsql
immutable
as $$
declare
  n integer;
  i integer;
  j integer;
begin
  if nums is null or cardinality(nums) <> 6 then
    return false;
  end if;

  foreach n in array nums loop
    if n < 1 or n > 45 then
      return false;
    end if;
  end loop;

  for i in 1..array_length(nums, 1) loop
    for j in i + 1..array_length(nums, 1) loop
      if nums[i] = nums[j] then
        return false;
      end if;
    end loop;
  end loop;

  return true;
end;
$$;

create table if not exists public.lottery_recommendations (
  id uuid primary key default gen_random_uuid(),
  user_input text,
  assistant_reply text not null,
  numbers integer[] not null,
  bonus_number integer not null,
  birth_date date,
  zodiac text,
  created_at timestamptz not null default now(),

  constraint lottery_recommendations_numbers_valid check (public.is_valid_lottery_numbers(numbers)),
  constraint lottery_recommendations_bonus_range check (bonus_number between 1 and 45),
  constraint lottery_recommendations_bonus_not_in_numbers check (not (bonus_number = any(numbers)))
);

create index if not exists lottery_recommendations_created_at_idx
  on public.lottery_recommendations (created_at desc);

create index if not exists lottery_recommendations_birth_date_idx
  on public.lottery_recommendations (birth_date desc);

alter table public.lottery_recommendations enable row level security;

drop policy if exists "Allow read access to recommendations" on public.lottery_recommendations;
create policy "Allow read access to recommendations"
on public.lottery_recommendations
for select
using (true);

drop policy if exists "Allow insert for authenticated users" on public.lottery_recommendations;
create policy "Allow insert for authenticated users"
on public.lottery_recommendations
for insert
to authenticated
with check (true);

